import purgecss from '@fullhuman/postcss-purgecss';

export default {
  plugins: [
    purgecss({
      content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './src/**/*.html'],
      defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      safelist: [
        // Classes Bootstrap critiques
        'container',
        'row',
        'col',
        'd-flex',
        'justify-content-center',
        'align-items-center',
        'text-center',
        'mt-',
        'mb-',
        'ms-',
        'me-',
        'p-',
        'pt-',
        'pb-',
        'ps-',
        'pe-',
        'm-',
        'my-',
        'mx-',
        // Classes de base
        'btn',
        'btn-primary',
        'btn-secondary',
        'btn-success',
        'btn-danger',
        'btn-warning',
        'btn-info',
        'btn-light',
        'btn-dark',
        'btn-link',
        'form-control',
        'form-label',
        'form-text',
        'form-check',
        'navbar',
        'navbar-nav',
        'navbar-brand',
        'navbar-toggler',
        'card',
        'card-body',
        'card-title',
        'card-text',
        'modal',
        'modal-dialog',
        'modal-content',
        'modal-header',
        'modal-body',
        'modal-footer',
        // Classes utilitaires
        'w-100',
        'h-100',
        'position-relative',
        'position-absolute',
        'overflow-hidden',
        'text-white',
        'text-dark',
        'bg-primary',
        'bg-secondary',
        'bg-success',
        'bg-danger',
        'bg-warning',
        'bg-info',
        'bg-light',
        'bg-dark',
        // Classes personnalisées critiques
        'hero-section',
        'about-section',
        'services-section',
        'portfolio-section',
        'contact-section',
        'footer-section',
      ],
    }),
  ],
};
